name: Release

on:
  workflow_dispatch:
    inputs:
      # TODO: Flag for publication.
      which-pypi:
        description: 'Which Python package index?'
        required: true
        type: choice
        options:
          - pypi
          - testpypi
        default: testpypi

jobs:

  initialize:
    uses: ./.github/workflows/reusable--initializer.yaml

  test:
    needs: [initialize]
    uses: ./.github/workflows/reusable--tester.yaml
    with:
      matrix-exclusions: '${{ needs.initialize.outputs.matrix-exclusions }}'
      platforms: '${{ needs.initialize.outputs.platforms }}'
      python-versions: '${{ needs.initialize.outputs.python-versions }}'
      python-descriptors: '${{ needs.initialize.outputs.python-descriptors }}'

  report:
    needs: [initialize, test]
    uses: ./.github/workflows/reusable--reporter.yaml
    with:
      python-version: '${{ fromJSON(needs.initialize.outputs.python-versions)[0] }}'

  docsgen:
    needs: [initialize, report]
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/reusable--documenter.yaml
    with:
      include-reports: true
      python-version: '${{ fromJSON(needs.initialize.outputs.python-versions)[0] }}'

  package:
    needs: [initialize, docsgen]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/reusable--packager.yaml
    with:
      pypi-api-urls: '${{ needs.initialize.outputs.pypi-api-urls }}'
      pypi-package-urls: '${{ needs.initialize.outputs.pypi-package-urls }}'
      python-version: '${{ fromJSON(needs.initialize.outputs.python-versions)[0] }}'
      which-pypi: '${{ inputs.which-pypi }}'
